name: nasaspaceapps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobkit_dashed_border: ^0.0.5

flutter:
  fonts:
    - family: Mozart
      fonts:
        - asset: fonts/Mozart.ttf
          weight: 700
  assets:
    - assets/background.png
    - assets/rocket.png
  uses-material-design: true
